version: '3'

services:
    app:
        build: .
        ports:
            - "8080:8080"
        environment:
            - PORT=8080
            - YOUTRACK_TEST_URL=${YOUTRACK_TEST_URL}
            - YOUTRACK_TEST_TOKEN=${YOUTRACK_TEST_TOKEN}
        restart: unless-stopped